### ISSUE TITLE
How do I make my website more searchable on Google?

### ISSUE THREAD

**Issue by lucien386** [lucien386/MusicXML2ABCNotationWebApp#48]
I have already submitted my website to Google Search Console

**Comment by xicheng87** [comment]
I think you want to look for "Search Engine Optimization" topic on the internet. You'd have to add more content & context to the website so that the crawler finds you more relevant. Furthermore, you'd have to attract more traffic to your site, and hopefully get more sites that reference you (as part of page rank algorithm). 

This is not a trivial task, and I would not put it as our top-priority for now. You can play with it but I think we better polish the front-end as the first step toward it.

**Comment by lucien386** [comment]
Could you give me some advice about polishing front-end?

**Comment by xicheng87** [comment]
Sorry for the late reply, I was bombarded with lots of things today. Will update you tomorrow with some concrete advice. Stay tuned.
